export const TYPING_INDICATOR_TTL = 1500
export const TYPING_INDICATOR_LEEWAY = 500
export const SET_CURSOR_WAIT = 500
export const DEFAULT_CONNECTION_TIMEOUT = 20 * 1000
export const MAX_INLINE_CONTENT_BYTES = 2000
